INSERT INTO books
(title, author, subject)
VALUES
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('To Kill A Mockingbird', 'Lee, Harper', "la di da di da di da di da di da di da di da"),
('Pride and Prejudice', 'Austen, Jane', "la di da di da di da di da di da di da di da"),
('War and Peace', 'Tolstoy', "la di da di da di da di da di da di da di da"),
('The Great Gatsby', 'Fitzgerald, F. Scott', "la di da di da di da di da di da di da di da"),
('Emma', 'Austen, Jane', "la di da di da di da di da di da di da di da");